# Generated by Django 2.0.1 on 2018-01-17 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectId', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('projectName', models.CharField(max_length=30)),
            ],
        ),
    ]
